# Generated by Django 4.0.1 on 2022-03-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyBill',
            fields=[
                ('billing_start_date', models.DateField(primary_key=True, serialize=False)),
                ('billing_end_date', models.DateField()),
                ('bill_month', models.DateField()),
                ('billing_days', models.IntegerField()),
                ('prior_excess_generation', models.IntegerField()),
                ('contribution', models.IntegerField()),
                ('useage', models.IntegerField()),
                ('billed_useage', models.IntegerField()),
                ('billed_amount', models.FloatField()),
                ('avg_daily_temp', models.IntegerField()),
                ('avg_daily_use', models.IntegerField()),
                ('basic_service_charge', models.FloatField()),
                ('theoretical_charge', models.FloatField()),
                ('theoretical_savings', models.FloatField()),
                ('price_per_kwh', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SunData',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('hours_sunlight', models.IntegerField()),
                ('sun_rise', models.TimeField()),
                ('sun_set', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.TextField()),
                ('actual', models.FloatField(null=True)),
                ('historic_avg', models.FloatField(null=True)),
                ('historic_record', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherObservations',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('observed_time', models.TimeField()),
                ('temperature', models.IntegerField()),
                ('dew_point', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind', models.TextField()),
                ('wind_speed', models.IntegerField()),
                ('wind_gust', models.IntegerField()),
                ('pressure', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('condition', models.TextField()),
            ],
        ),
    ]
