# Generated by Django 4.0.1 on 2022-03-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyUseage',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('panelName', models.TextField()),
                ('circuitName', models.TextField()),
                ('useage', models.FloatField()),
            ],
        ),
    ]
