# Generated by Django 4.0.1 on 2022-03-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_solargeneration_vueenergyuseage_delete_energyuseage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solargeneration',
            name='time',
            field=models.TimeField(),
        ),
    ]
