# Generated by Django 4.0.1 on 2022-03-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_solargeneration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solargeneration',
            name='generationKwh',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='solargeneration',
            name='generationWh',
            field=models.FloatField(null=True),
        ),
    ]
