# Generated by Django 4.0.1 on 2022-03-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_solargeneration_generationkwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energybill',
            name='actual_price_per_kwh',
            field=models.FloatField(null=True),
        ),
    ]
